### ISSUE TITLE
Create a package for this

### ISSUE THREAD

**Issue by cpetry** [Unity-Technologies/VHACD-deprecated#11]
I would like to use the UPM for this.
Can you create a package.json and set it up as a unity package?

**Comment by at669** [comment]
Hi @cpetry, the package version of this repo is a WIP on the [`package` branch](https://github.com/Unity-Technologies/VHACD/tree/package)--you can test it out by doing the following:

1. Open the Package Manager from `Window` -> `Package Manager`.
2. In the Package Manager window, find and click the `+` button in the upper lefthand corner of the window. Select `Add package from git URL...`.
3. Enter the following URL:
    `https://github.com/Unity-Technologies/VHACD.git?path=/com.unity.robotics.vhacd#package`

Please note that this branch is still a WIP. Hope this helps!

**Comment by cpetry** [comment]
Ah alright! Didn't see the package branch.
Thanks for the hint!
