### ISSUE TITLE
VHACD appear to have a hard time with stairs.

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/VHACD-deprecated#14]
Hi,

I found this repo and was trying it out on a simple stairs mesh (attached below), using the `mesh-generator` branch's code:

<img width="338" alt="Screen Shot 2021-12-04 at 21 03 25" src="https://user-images.githubusercontent.com/1484279/144710479-a81049a4-ed99-4c99-bd52-ea211229f103.png">

I find the algorithm unable to distinguish among staircases, is there any way to instruct it to prefer a certain way of decomposition? I tried quite a few parameter adjustment to no avail.

[simple-stairs.fbx.zip](https://github.com/Unity-Technologies/VHACD/files/7653976/simple-stairs.fbx.zip)

Thx!

**Comment by at669** [comment]
Hi, thanks for the report! First and foremost, please note that the `mesh-generator` branch and all feature branches are in active development. Its features and API are subject to significant change as development progresses. 

Could you elaborate on your use case and needs for this tool? 

The first parameter I would suggest modifying is the `Resolution`. Leaving all of the parameters at their defaults and increasing the `Resolution` to `1000000` gave me the following result--based on your use case, would the attached image have enough physical fidelity? You can continue to increase this value further for a higher maximum number of voxels generated during the voxelization stage.

![Screen Shot 2021-12-06 at 9 39 24 AM](https://user-images.githubusercontent.com/31416491/144894890-2988eb7e-a0ef-43d2-866e-232b8086827d.png)

You can learn more about each of the VHACD parameters on the main [README](https://github.com/Unity-Technologies/VHACD/tree/mesh-generator#parameters).

**Comment by bitinn** [comment]
@at669 thx, I tried it with 1,000,000 resolution and indeed it works as expected.

<img width="328" alt="Screen Shot 2021-12-10 at 0 05 25" src="https://user-images.githubusercontent.com/1484279/145435766-b57324d0-424d-4a66-8c34-9f87cabcd9a1.png">

PS: I wonder if there are ways for me to group these generated meshes into a single FBX file, unfortunately FBX Exporter doesn't do this even with "Export Unrendered" enabled.
