### ISSUE TITLE
VHACD dll has been compiled with DEBUG -> So requires VS dlls 

### ISSUE THREAD

**Issue by poke50uk** [Unity-Technologies/VHACD-deprecated#2]
![unknown](https://user-images.githubusercontent.com/12011520/105050410-a87ea180-5a65-11eb-9fdc-b5f560e8d255.png)

As VHACD dll has been compiled with Debug, it means that end users can't run as they are often missing VCOMP140D.DLL

This is closer to what's expected
![unknown1](https://user-images.githubusercontent.com/12011520/105050729-fc898600-5a65-11eb-8ff0-5b4d7af57828.png)

**Comment by LaurieCheers-unity** [comment]
Fixed.

**Comment by poke50uk** [comment]
Excellent - thanks!
